// page-transformer/src/components/footer.vue
<style scoped>
#tmall-copyright {
    border-top: 2px solid #FF0036;
    background: #000;
    text-align: left;
    min-height: 40px;
}
#tmall-copyright p a {
    margin-right: 3px;
    color: #fff;
    white-space: nowrap;
}
</style>

<template>
    <div id="tmall-copyright">
        <div class="mui-global-fragment-load" data-fragment="tmbase/mui_footer_link"
            data-spm-anchor-id="a1z0i.26822550.a2226n1.i1.641c426aSuzmqI">
            <p class="footer-tmallinfo">
                <a href="//pages.tmall.com/wow/seller/act/zhaoshangproduce" target="_blank">关于天猫</a>
                <a href="//service.tmall.com/support/tmall/tmallHelp.htm" target="_blank">商家服务大厅</a>
                <a href="//open.taobao.com" target="_blank">开放平台</a>
                <a href="//job.alibaba.com/zhaopin/index.htm" target="_blank">诚聘英才</a>
                <a href="//consumerservice.taobao.com/contact-us" target="_blank">联系我们</a>
                <a href="//xtao.tmall.com?tracelog=tmallfoot" target="_blank">网站合作</a>
                <a href="//terms.alicdn.com/legal-agreement/terms/suit_bu1_tmall/suit_bu1_tmall201801121425_43176.html"
                    target="_blank">法律声明</a>
                <a href="//terms.alicdn.com/legal-agreement/terms/suit_bu1_tmall/suit_bu1_tmall201801031144_60809.html"
                    target="_blank">隐私权政策</a>
                <a href="http://ipp.alibabagroup.com/" target="_blank">知识产权</a>
                <a href="//jubao.alibaba.com/index.html?site=TMALL" target="_blank">廉正举报</a>
                <a class="footer-fp-rule" style="display:none;" href="//rule.tmall.com/trulecycle.htm"
                    target="_blank">规则意见征集</a>
                <a class="footer-fp-rule"
                    href="//terms.alicdn.com/legal-agreement/terms/suit_bu1_tmall/suit_bu1_tmall202105131215_46119.html"
                    target="_blank">不当竞争举报</a>
            </p>
            <p class="footer-otherlink">
                <a href="http://www.alibabagroup.com/cn/global/home" target="_blank">阿里巴巴集团</a>|
                <a href="//www.taobao.com" target="_blank">淘宝网</a> |
                <a href="//www.tmall.com/" target="_blank">天猫</a> |
                <a href="//ju.taobao.com/" target="_blank">聚划算</a> |
                <a href="http://www.aliexpress.com/" target="_blank">全球速卖通</a> |
                <a href="http://www.alibaba.com/" target="_blank">阿里巴巴国际交易市场</a>|
                <a href="//www.1688.com/" target="_blank">1688</a> |
                <a href="//www.alimama.com/" target="_blank">阿里妈妈</a> |
                <a href="//www.fliggy.com/" target="_blank">飞猪</a> |
                <a href="http://www.aliyun.com/" target="_blank">阿里云计算</a> |
                <a href="http://www.alios.cn/" target="_blank">AliOS</a> |
                <a href="//aliqin.tmall.com/" target="_blank">阿里通信</a> |
                <a href="http://www.net.cn/" target="_blank">万网</a> |
                <a href="http://www.autonavi.com/" target="_blank">高德</a> |
                <a href="http://www.uc.cn/" target="_blank">UC</a> |
                <a href="http://www.umeng.com/" target="_blank">友盟</a> |
                <a href="http://www.xiami.com/" target="_blank">虾米</a> |
                <a href="http://www.dingtalk.com/?lwfrom=20150205115110773" target="_blank">钉钉</a> |
                <a href="https://www.alipay.com" target="_blank">支付宝</a> |
                <a href="https://s.alibaba.com?scene=clinks" target="_blank">阿里安全</a>
            </p>
        </div>
    </div>
</template>

// page-transformer-svelte/src/lib/footer/Footer.svelte
<footer>
    <div id="tmall-copyright">
        <div class="mui-global-fragment-load" data-fragment="tmbase/mui_footer_link"
            data-spm-anchor-id="a1z0i.26822550.a2226n1.i1.641c426aSuzmqI">
            <p class="footer-tmallinfo">
                <a href="//pages.tmall.com/wow/seller/act/zhaoshangproduce" target="_blank">关于天猫</a>
                <a href="//service.tmall.com/support/tmall/tmallHelp.htm" target="_blank">商家服务大厅</a>
                <a href="//open.taobao.com" target="_blank">开放平台</a>
                <a href="//job.alibaba.com/zhaopin/index.htm" target="_blank">诚聘英才</a>
                <a href="//consumerservice.taobao.com/contact-us" target="_blank">联系我们</a>
                <a href="//xtao.tmall.com?tracelog=tmallfoot" target="_blank">网站合作</a>
                <a href="//terms.alicdn.com/legal-agreement/terms/suit_bu1_tmall/suit_bu1_tmall201801121425_43176.html"
                    target="_blank">法律声明</a>
                <a href="//terms.alicdn.com/legal-agreement/terms/suit_bu1_tmall/suit_bu1_tmall201801031144_60809.html"
                    target="_blank">隐私权政策</a>
                <a href="http://ipp.alibabagroup.com/" target="_blank">知识产权</a>
                <a href="//jubao.alibaba.com/index.html?site=TMALL" target="_blank">廉正举报</a>
                <a class="footer-fp-rule" style="display:none;" href="//rule.tmall.com/trulecycle.htm"
                    target="_blank">规则意见征集</a>
                <a class="footer-fp-rule"
                    href="//terms.alicdn.com/legal-agreement/terms/suit_bu1_tmall/suit_bu1_tmall202105131215_46119.html"
                    target="_blank">不当竞争举报</a>
            </p>
            <p class="footer-otherlink">
                <a href="http://www.alibabagroup.com/cn/global/home" target="_blank">阿里巴巴集团</a>|
                <a href="//www.taobao.com" target="_blank">淘宝网</a> |
                <a href="//www.tmall.com/" target="_blank">天猫</a> |
                <a href="//ju.taobao.com/" target="_blank">聚划算</a> |
                <a href="http://www.aliexpress.com/" target="_blank">全球速卖通</a> |
                <a href="http://www.alibaba.com/" target="_blank">阿里巴巴国际交易市场</a>|
                <a href="//www.1688.com/" target="_blank">1688</a> |
                <a href="//www.alimama.com/" target="_blank">阿里妈妈</a> |
                <a href="//www.fliggy.com/" target="_blank">飞猪</a> |
                <a href="http://www.aliyun.com/" target="_blank">阿里云计算</a> |
                <a href="http://www.alios.cn/" target="_blank">AliOS</a> |
                <a href="//aliqin.tmall.com/" target="_blank">阿里通信</a> |
                <a href="http://www.net.cn/" target="_blank">万网</a> |
                <a href="http://www.autonavi.com/" target="_blank">高德</a> |
                <a href="http://www.uc.cn/" target="_blank">UC</a> |
                <a href="http://www.umeng.com/" target="_blank">友盟</a> |
                <a href="http://www.xiami.com/" target="_blank">虾米</a> |
                <a href="http://www.dingtalk.com/?lwfrom=20150205115110773" target="_blank">钉钉</a> |
                <a href="https://www.alipay.com" target="_blank">支付宝</a> |
                <a href="https://s.alibaba.com?scene=clinks" target="_blank">阿里安全</a>
            </p>
        </div>
    </div>
</footer>

<style>
#tmall-copyright {
    border-top: 2px solid #FF0036;
    background: #000;
    text-align: left;
    min-height: 40px;
}
#tmall-copyright p a {
    margin-right: 3px;
    color: #fff;
    white-space: nowrap;
}
</style>
